<farmyard>:
    name: 'farmyard'
    FloatLayout:
        size_hint: None, None

    DPEAButton:
        #Go back button
        size: 175, 100
        center_x: root.width * 0.8
        center_y: root.height * 0.1
        color: 1, 0, 0, 1

        text: "Wanna go back?"
        on_press: root.go_back()

    ImageButton:
        id:another_logo
        source: "pika.jpg"
        size: 100, 100
        x: root.width * 0.7
        y: root.height * 0.7
        on_press: root.animate()




